---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-credentials
  namespace: traefik
spec:
  encryptedData:
    api-token: AgCBJI3MEYZjcQ3HNOB8F+X52xOrwipSUpZil2uNat/E1jSRWhyVWeZ9UUJkr1ik8f/80M2WBRVVAdP2NqdF3k3cDjj+ksqOhlpCpB0iM2fgt44dAjTlGhY+CsvxeYDzivMKIGF39Wk4yd0QLQOBevoeCHkYdZfL37bBda95FdgDUPrEQVxe+mQ2ccGxox9D9g24Fgw88kUYXwuqfJefcazcoESDdIv104oeG+1E3IYD/qcm9PuQOmsKFYzC/V+BSMLjDz6K1a+VRCoQNCz9PA6UvFefNYdfxVnEQPP3RnZaFp8vyLsJ+VoeDIGjlcUE1pgFGzECkoEklx3nPnpsfXZAYJ11eThFDvTgjXL9Kfja9KygwD+RRYdH7F2WirR5Xi0Z1FORKy0GHFGoj/MWzzb5GrzUJZ4VyfveqrInL3yO67IMuihAWeE9geT3puk5hFzvtiVKwIfYJb+hpydrb7Ac/Vz4R79L9XpZfCv6cP2uwJnwPrWPeRNi68UYtW2a3E39xtKpgcJ5/MQXhgUvxXUzAJJ+nFScA2YffcHvzINCc7sKXuye3aIRQNyCgh9j1M9+XAyYUIghVq6X7uD5PcRZV4eolv+UyhGLPFBzaQt/Uh4h69ap9RhX4ZhduowwMgbMWKAHgqBM5dMsdkmS8atbSH1f/UoToN73jePNKczGYbeiYZif8mhSinfj7vjHetaN4zhDPkVA7EjV+T9yXdJQ5rS+yFIo0J88W3AL1Q1opi6K8uzfKZFt
    email: AgCE/uzn378JeSWYvR84yjNjDxdBQhik1gvtOxOegcipmQUfz47rx/P3fjVWrj+dHC1OLnIEz58hPLyAf9kY4kLAwppNllDGOPaiMpUx+jbarG7qau44B1oZqIC3/Vpd/8zw43ZUC+adqHnTJNJUUdKXXQLY5Btq7JZwM3YGq1fxCMCg/BpCSpH0/ZWUKQgD67+P3PBbXfOgd+sbt+YqxpjJE4vPdxcETfxs0EkU9zGMIJ5aasclDYbd0Wn4IsBBf431KZ69EY8ZZhoQj92H7po2azTc0trk6UAyDIsHfGUgczrL+XNNGP0gYoRvmRDfp+K6ZaIHiuKOeBDq2X7PY+sJgP2Bp+Ey0rYWGyJSUwd88a/esjDgy0xGN6n5VZ1R99OZmTKTQiXHrIOOOTNo90fzGaNgC0XRw9L1HHuqOdy09imojFWaUY8zlI3KD90ptqOTc8SOhDN7Jnm6VRNOUED4F8q4mkwQkqYFE+If/edPZ5bTPrHEwxefxZbzKm53xSXlXd3zikMenfQUPkTVpG4CzfGvBoLDo+GLzf6j0YfzDZF6Pg14+oe4gF43T0J2KTE1IB65fDS8wF3HR9vMfpfn3PUsZR9/oUdeb4Y05DEnU9////ve/P7jA6tKsiAevYmHjzY32Q9JIW13gJrIzePvTNAbj8KSYHek1a3RmCwaSetbKBq7IYEyIA6RErcGq4iK6H1djN1r1L325A1VroI3lhA7L4U=
  template:
    metadata:
      name: cloudflare-credentials
      namespace: traefik
