---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAGSOiWFDVdPD6Fi59jwp+tI+wNp+5thgSJxbnslLfTSfa4nt9Z17T/c7eZ/V8cEmv8m2l0PuveDi8GdsPykrFIZP7AKTqBR2vyT7X5+2aOEsGyUuV8PfY38tFmu34dPMXV6kLXWDuUpbsv12MKqNXKT7HF37xfCf98aOT+lOv5E02rGlpEyGjKEwWzRAKoXd5Dlk/qllp4HkRwctApTqMvdgJHt7KCKLSP5mXEX/Xw70XhZrA9gDOj/78thde/ZkKWy7PxvPpLkSPinWjwLQOrjt5QVHqGUgvnzYKNTxCWiHLSto08sE7yicoXvi3ct0W6ErbMxD+QXui56bpofzd/dxPaOSyqo+rXKUYw0PAlQVnECYytGC7HwXvQ7xp8yoSZMRq/XcG1R75tVWtnflrgbk7YAacY+gEkCxUZhRTUPcmuRoBMR6nnJpEvOUn7zYxT54ImRT79SVg1m++8/uCdvYzz57Z4TT37v4/ww5+avQ257rjci+HAKVD+jf3r8k2M14diMm7kwOCfhnabFxLlJKIUOCjRwDrDOeXRuouXmYjz8p2wNw7s5B0ZygA3c7vXMzrsRjnU3KOdc7rnjyy1+st208ZqPe98WZSAQi/i8HlDBA6M3dSZf+N0LlEEZ7HHe6BO/NIuE/qDRQNjt/+RHGzpgGoIxax4ZcwVd8j4BFqztsyHF5eZ5CM0CpBXOkyudwIu5Tz/vLvJMzSlVDqJsiNeog4XyNZkaLY1Ls1ZRw==
    admin-user: AgBebfzjoe8Wu+VWYnFeW4trqM+DL2XuzjclUdcnDNDn5j3O8xU5Gfq4B/8nVkn9Ibz3N9kVbvk+LYuLAsehibE0RM9TDx2bYrx8yD2fQBwQrKPz1jD7twwWKi99+a3TiNiw83AM3ESy+oxZSageaaqJozvHNKuCXJOs7y+2yTiPs8L3GGR+VK5olhYSJdaSSwa2Jz7ZXcrGpizD/7wQfWtqVgCmz1tlxJUYVCiO/AxWsaZkmp7wZlrNc+ex8UcQruB8Jy0rtlDFQgxeh/RPYOkRr6SdloNYoohUg55swFNjjGwbMQOPcGo3WNbwn55F7q8cx7B/INr2gTYHX406yTdEvzojodmd76R4b7gctLdoHtPV8nih6VFxDj/6FNcN8Y46JwdaSogtj0bLJOmeSZX7Xp5f38OQEDpc2Dxdg39SoeRTykh34Ydcqrt7OTfkoA7pQSFk0CPzOlOfhsK4buhCwWLghCQK6mngjOT+Gb5yjPm5a+FSYLO7OcKEvJ3gy08+YMMqYioYcmI5kwRIXW9Nppk7r5vO7l2a/6TMY6ESjU/so8FdMckbdf0Brk2URb0O1TYcOqIPjYQf0em+e2qZ9N1A10F65PJWYLC96dXbc+2jNaCfXsoiT5KBNrBtvMcECs+Ql/njDD3TmK+amqVwtNCCOtkUzxag6gvCKm3DKYhCH11U28k9wTbfwfwoKCj+hWL2jw==
  template:
    metadata:
      name: grafana-credentials
      namespace: monitoring
