# ArgoCD Application for Loki
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/viperaxz/Proxmox-K8S.git
    targetRevision: main
    path: argocd/helm-charts/loki
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/template/metadata/annotations
        - /spec/volumeClaimTemplates/0/status
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.template.metadata
        - .metadata.annotations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
